version: '3.0'
services:
    database:
        labels:
            - traefik.enable=false

    php:
        depends_on:
            - database
            - smtp
        labels:
            - traefik.enable=false

    httpd:
        labels:
            - traefik.enable=true
            - traefik.http.routers.ad_checker_httpd.rule=Host(`ad-checker.local`)
            - traefik.http.routers.ad_checker_httpd.entryPoints=web

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        environment:
            - PMA_HOST=database
        labels:
            - traefik.enable=true
            - traefik.http.routers.ad_checker_phpmyadmin.rule=Host(`phpmyadmin.ad-checker.local`)
            - traefik.http.routers.ad_checker_phpmyadmin.entryPoints=web

    smtp:
        image: djfarrelly/maildev
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.ad_checker_maildev.rule=Host(`maildev.ad-checker.local`)
            - traefik.http.routers.ad_checker_maildev.entryPoints=web
            - traefik.http.services.ad_checker_maildev.loadbalancer.server.port=80

    traefik:
        image: traefik:v2.3
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./dockerfiles/traefik/traefik.toml:/etc/traefik/traefik.toml
            - ./dockerfiles/traefik/acme.json:/acme.json
